version: '3'
services:
  REST:
    build : ./
    REST/REST/app/src/java
    volumes:
      - ./
      REST/REST/app/src/java:/usr/src/app
    ports:
      - "8050:10006"
  SOAP:
    build : ./SOAP/client
    volumes:
      - ./SOAP/client:/usr/src/app
     ports :
       -"8060:10000"
